server:
    port: 9090
    servlet:
        context-path: /Shopme
spring:
    application:
        name: ShopmeFrontend
    datasource:
        password: abc@123
        url: jdbc:mysql://localhost:3306/shopmedb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    output:
        ansi:
            enabled: ALWAYS
    security:
        oauth2:
            client:
                registration:
                  google:
                      client-id: 52701474471-ntd4huegl8unjnlo68mrrp4cll0pll20.apps.googleusercontent.com
                      client-secret: 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
                      scope:
                          - email
                          - profile
                  facebook:
                      client-id: 2453986105064573
                      client-secret: 795f6bc6fc16b28bf9bd5dc164e08b2f
                      scope:
                        - email
                        - public_profile



