server:
    port: 9090
    servlet:
        context-path: /Shopme
spring:
    application:
        name: ShopmeFrontend
    datasource:
        password: ${DB_PASSWORD}
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    output:
        ansi:
            enabled: ALWAYS
    security:
        oauth2:
            client:
                registration:
                  google:
                      client-id: 52701474471-ntd4huegl8unjnlo68mrrp4cll0pll20.apps.googleusercontent.com
                      client-secret: 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
                      scope:
                          - email
                          - profile
                  facebook:
                      client-id: 2453986105064573
                      client-secret: 795f6bc6fc16b28bf9bd5dc164e08b2f
                      scope:
                        - email
                        - public_profile
paypal:
    client-id: AZb9q-xIQxAKTQS1XOuhecvxCXIHaqa08KlJWmvf1rnTdKjiTeSnyqEAa7mx00q1vr_h5Nx7p1hJqX7B
    client-secret: EETu6ZHLXtONwP_HqbSyVsAjqORKQscokK0S0fczPP-yEgvyigHN0sWcXpFZ64bK0Z4hyS-Ls8OlWQnl



