[build]
builder = "paketobuildpacks/builder:base"

[build.env]
# Skip running tests during build
MAVEN_OPTS = "-Dmaven.test.skip=true"

[service]
# Tell Railway where the backend module is
root = "ShopmeWebParent/ShopmeBackend"

[deploy]
startCommand = "java -jar target/ShopmeBackend-0.0.1-SNAPSHOT.jar"

